[project]
name = "erpnext_france"
authors = [
  { name = "SCOPEN", email = "contact@scopen.fr"},
  { name = "Britlog", email = "contact@scopen.fr"},
  { name = "Frappe Technologies Pvt Ltd", email = "developers@frappe.io"}
]
description = "App for french localization"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # core dependencies
    "zeep~=4.2",
    "sepaxml~=2.5.0",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.black]
line-length = 99

[tool.isort]
line_length = 99
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
indent = "\t"
